### ISSUE TITLE
Use of [SerializeField] generates tons of compiler warnings

### ISSUE THREAD

**Issue by BogdanAlexandru** [atil/fpscontroller#1]
Great asset, I'm extending it for my game right now :)

However, you use lots of

``` 
[SerializeField]
private Footsteps _footsteps;
```

which generates lots of

![image](https://user-images.githubusercontent.com/5050074/63635815-b1e8bc00-c66f-11e9-9219-0eb6f36d659f.png)

So it would help if these were public.

**Comment by atil** [comment]
Thanks. Gonna take care of this.

**Comment by atil** [comment]
Added `= default` to `[SerializeField]` variables in 5ad78d6f
